# Generated by Django 2.2.12 on 2022-05-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_modal', models.CharField(max_length=250)),
                ('content_modal', models.TextField()),
            ],
        ),
    ]
